# ==========================================
# Spring Boot Configuration
# ==========================================

spring.application.name=Style-Finder
spring.config.import=optional:file:.env[.properties]
server.forward-headers-strategy=framework

# --- SERVER ---
#server.port=${SERVER_PORT}
# --- DATABASE (AWS RDS PostgreSQL) ---
#spring.datasource.url=${DB_HOST}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
#spring.datasource.name=${DB_NAME}

spring.datasource.url=${DB_HOST_LOCAL:${DB_HOST}}
spring.datasource.username=${DB_USER_LOCAL:${DB_USER}}
spring.datasource.password=${DB_PASS_LOCAL:${DB_PASS}}
spring.datasource.name=${DB_NAME_LOCAL:${DB_NAME}}

spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE / JPA ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' automatically create or update our SQL tables based on our jpa entities
spring.jpa.hibernate.ddl-auto=update
# Prints the SQL queries to the terminal for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

b2.enabled=${B2_ENABLED:true}
b2.accessKeyId=${B2_ACCESS_KEY}
b2.secretKey=${B2_SECRET_KEY}
b2.endpoint=${B2_ENDPOINT}
b2.bucketName=${B2_BUCKET_NAME}


# Show error details only when explicitly requested to avoid leaking internals by default
server.error.include-message=on_param
server.error.include-binding-errors=on_param