# ==========================================
# Spring Boot Configuration
# ==========================================

spring.application.name=Style-Finder
spring.config.import=optional:file:.env[.properties]
# --- SERVER ---
server.port=${SERVER_PORT}

# --- DATABASE (AWS RDS PostgreSQL) ---
spring.datasource.url=${DB_HOST}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.name=${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE / JPA ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' automatically create or update our SQL tables based on our jpa entities
spring.jpa.hibernate.ddl-auto=update
# Prints the SQL queries to the terminal for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true