spring.application.name=Style-Finder

spring.datasource.url=jdbc:postgresql://style-finder-db1.censy6i8kbdm.us-east-1.rds.amazonaws.com:5432/stylefinder_db
spring.datasource.username=admin_posgres
spring.datasource.password=StyleFinderTech*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


